### PR TITLE
Use PyVEP library for doing BrowserID verification.

### PR DESCRIPTION
**Pull request by rfk**
PyVEP provides a DummyVerifier class for doing testing with properly-formed but invalid BrowserID assertions.  It will also make it easy to switch over to local verification once the VEP certificate format is
finalized.

(We could do local verification right now by replacing vep.RemoteVerifier() with vep.LocalVerifier(), but that opens up the possibility of breakage when the identity team changes things in the spec)

Thoughts?

### CODE REVIEW

**Comment by tarekziade** [comment]
That looks cool to run the tests against the SQL backend, so yay!

The other stuff that's quite urgent is to have a way to deactivate browser id on the sauropod server - https://bugzilla.mozilla.org/show_bug.cgi?id=708088

**Comment by rfk** [comment]
I've done a quick patch for it here: https://github.com/mozilla/sauropod/pull/16.  It accepts well-formed browserid assertions like the live verifier does, but just parses the info out of them rather than validating the signatures.

It still needs a knob to turn it on for testing servers and off for production, but that sounds like a job for @rtilder...

**Comment by tarekziade** [comment]
awesome ! 

r+ to pull in the current patch (also, let's add pyvep in prod-reqs.txt)

**Comment by ianb** [comment]
r+ (but a merge conflict?)

**Comment by rfk** [comment]
Thanks, merged by hand.  Conflict was in dev-reqs.txt, nothing serious :-)

**Pull request closed without merging**
